gui:
  showIcons: true
  border: rounded
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#8c97ff" # accent
      - bold
    inactiveBorderColor:
      - "#636b7b" # dim
    optionsTextColor:
      - "#f5c56a" # yellow
    selectedLineBgColor:
      - "#22273a" # selection
    selectedRangeBgColor:
      - "#22273a" # selection
    cherryPickedCommitBgColor:
      - "#f5c56a" # yellow
    cherryPickedCommitFgColor:
      - "#17181d" # bg
    unstagedChangesColor:
      - "#f5c56a" # dirty
    defaultFgColor:
      - "#e6e9ef" # foreground
    searchingActiveBorderColor:
      - "#f5c56a" # yellow
      - bold
git:
  pagers:
    - colorArg: always
      pager: delta --paging=never
